# Generated by Django 5.1.1 on 2025-01-30 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('registrado_por_qr', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
