# Generated by Django 5.1.1 on 2025-01-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0003_registroasistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='registrado_por_qr',
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
